# Determine the IP address information from the physical interface.
---
- name: IP address information (from physical interface)
  set_fact:
    opencontrail_host_address: "{{ hostvars[inventory_hostname]['ansible_' + opencontrail_host_interface]['ipv4']['address'] }}"
    opencontrail_host_netmask: "{{ hostvars[inventory_hostname]['ansible_' + opencontrail_host_interface]['ipv4']['netmask'] }}"
    opencontrail_host_gateway: "{{ hostvars[inventory_hostname]['ansible_' + opencontrail_host_interface]['ipv4']['gateway'] if 'gateway' in hostvars[inventory_hostname]['ansible_' + opencontrail_host_interface]['ipv4'] else None }}"

- set_fact:
    opencontrail_host_prefixlen: "{{ opencontrail_host_netmask | netmask2prefixlen }}"
- set_fact:
    opencontrail_host_ipaddr: "{{ [opencontrail_host_address, opencontrail_host_prefixlen] | join('/') }}"
