---
- name: Ensure configuration directory exists
  file: path="/etc/contrail" state=directory

- file: path="{{ opencontrail_all_kube_config_dir }}" state=directory

- name: Ensure log directory exists
  file: path="/var/log/contrail" state=directory

- name: Configuration files
  template: src="{{ item }}.j2" dest="/etc/contrail/{{ item }}"
  with_items:
    - contrail-api.conf
    - contrail-schema.conf

- name: Install configuration services
  copy: src="{{item}}" dest=/etc/systemd/system
  with_items:
    - contrail-api.service
    - contrail-schema.service
    - ifmap-server.service
  notify:
    - reload systemd

- name: Install configuration services (from templates)
  template: src="{{ item }}.j2" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - kube-network-manager.service
  notify:
    - reload systemd

- name: Network manager configuration
  template: src=kube-network.conf.j2 dest={{ opencontrail_all_kube_config_dir }}/network.conf
  notify:
    - restart kube-network-manager

- name: Start configuration services
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - contrail-api
    - contrail-schema
    - ifmap-server

#  kube-network-manager can only be started after origin-master is defined.
- name: Enable kube-network-manager
  service: name=kube-network-manager enabled=yes
